package com.example.androidprojectiti.dto.MealResponse

import android.os.Parcel
import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.versionedparcelable.VersionedParcelize
import kotlinx.parcelize.Parcelize

@Parcelize
@Entity
data class Meal(
    val dateModified: String?,
    @PrimaryKey
    val idMeal: String,
    val strArea: String,
    val strCategory: String,
    val strCreativeCommonsConfirmed: String?,
    val strDrinkAlternate: String?,
    val strImageSource: String?,
    val strIngredient1: String?,
    val strIngredient10: String?,
    val strIngredient11: String?,
    val strIngredient12: String?,
    val strIngredient13: String?,
    val strIngredient14: String?,
    val strIngredient15: String?,
    val strIngredient16: String?,
    val strIngredient17: String?,
    val strIngredient18: String?,
    val strIngredient19: String?,
    val strIngredient2: String?,
    val strIngredient20: String?,
    val strIngredient3: String?,
    val strIngredient4: String?,
    val strIngredient5: String?,
    val strIngredient6: String?,
    val strIngredient7: String?,
    val strIngredient8: String?,
    val strIngredient9: String?,
    val strInstructions: String?,
    val strMeal: String?,
    val strMealThumb: String?,
    val strMeasure1: String?,
    val strMeasure10: String?,
    val strMeasure11: String?,
    val strMeasure12: String?,
    val strMeasure13: String?,
    val strMeasure14: String?,
    val strMeasure15: String?,
    val strMeasure16: String?,
    val strMeasure17: String?,
    val strMeasure18: String?,
    val strMeasure19: String?,
    val strMeasure2: String?,
    val strMeasure20: String?,
    val strMeasure3: String?,
    val strMeasure4: String?,
    val strMeasure5: String?,
    val strMeasure6: String?,
    val strMeasure7: String?,
    val strMeasure8: String?,
    val strMeasure9: String?,
    val strSource: String?,
    val strTags: String?,
    val strYoutube: String?,
) : Parcelable{
    // Method to get a Meal with default values for null attributes
    fun putDefaults(): Meal {
        return this.copy(
            dateModified = dateModified ?: "Default Date",
            strCreativeCommonsConfirmed = strCreativeCommonsConfirmed ?: "Unknown",
            strDrinkAlternate = strDrinkAlternate ?: "Not Available",
            strImageSource = strImageSource ?: "No Image",
            strIngredient1 = strIngredient1 ?: "Unknown Ingredient",
            strIngredient10 = strIngredient10 ?: "Unknown Ingredient",
            strIngredient11 = strIngredient11 ?: "Unknown Ingredient",
            strIngredient12 = strIngredient12 ?: "Unknown Ingredient",
            strIngredient13 = strIngredient13 ?: "Unknown Ingredient",
            strIngredient14 = strIngredient14 ?: "Unknown Ingredient",
            strIngredient15 = strIngredient15 ?: "Unknown Ingredient",
            strIngredient16 = strIngredient16 ?: "Unknown Ingredient",
            strIngredient17 = strIngredient17 ?: "Unknown Ingredient",
            strIngredient18 = strIngredient18 ?: "Unknown Ingredient",
            strIngredient19 = strIngredient19 ?: "Unknown Ingredient",
            strIngredient2 = strIngredient2 ?: "Unknown Ingredient",
            strIngredient20 = strIngredient20 ?: "Unknown Ingredient",
            strIngredient3 = strIngredient3 ?: "Unknown Ingredient",
            strIngredient4 = strIngredient4 ?: "Unknown Ingredient",
            strIngredient5 = strIngredient5 ?: "Unknown Ingredient",
            strIngredient6 = strIngredient6 ?: "Unknown Ingredient",
            strIngredient7 = strIngredient7 ?: "Unknown Ingredient",
            strIngredient8 = strIngredient8 ?: "Unknown Ingredient",
            strIngredient9 = strIngredient9 ?: "Unknown Ingredient",
            strInstructions = strInstructions ?: "Instructions not available",
            strMeal = strMeal ?: "Unknown Meal",
            strMealThumb = strMealThumb ?: "No Thumbnail",
            strMeasure1 = strMeasure1 ?: "Unknown Measurement",
            strMeasure10 = strMeasure10 ?: "Unknown Measurement",
            strMeasure11 = strMeasure11 ?: "Unknown Measurement",
            strMeasure12 = strMeasure12 ?: "Unknown Measurement",
            strMeasure13 = strMeasure13 ?: "Unknown Measurement",
            strMeasure14 = strMeasure14 ?: "Unknown Measurement",
            strMeasure15 = strMeasure15 ?: "Unknown Measurement",
            strMeasure16 = strMeasure16 ?: "Unknown Measurement",
            strMeasure17 = strMeasure17 ?: "Unknown Measurement",
            strMeasure18 = strMeasure18 ?: "Unknown Measurement",
            strMeasure19 = strMeasure19 ?: "Unknown Measurement",
            strMeasure2 = strMeasure2 ?: "Unknown Measurement",
            strMeasure20 = strMeasure20 ?: "Unknown Measurement",
            strMeasure3 = strMeasure3 ?: "Unknown Measurement",
            strMeasure4 = strMeasure4 ?: "Unknown Measurement",
            strMeasure5 = strMeasure5 ?: "Unknown Measurement",
            strMeasure6 = strMeasure6 ?: "Unknown Measurement",
            strMeasure7 = strMeasure7 ?: "Unknown Measurement",
            strMeasure8 = strMeasure8 ?: "Unknown Measurement",
            strMeasure9 = strMeasure9 ?: "Unknown Measurement",
            strSource = strSource ?: "No Source",
            strTags = strTags ?: "No Tags",
            strYoutube = strYoutube ?: "No YouTube Link"
        )
    }
}